-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_threads.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE simpleforum_threads (
  sf_thread_id BIGSERIAL NOT NULL,
  sf_page_id BIGINT NOT NULL,
  sf_forum_page_id BIGINT NOT NULL,
  sf_subject VARCHAR(255) NOT NULL,
  sf_created TIMESTAMPTZ NOT NULL,
  sf_creator BIGINT NOT NULL,
  sf_last_reply TIMESTAMPTZ DEFAULT NULL,
  sf_last_reply_user BIGINT DEFAULT NULL,
  PRIMARY KEY(sf_thread_id)
);

CREATE UNIQUE INDEX sf_thread_page ON simpleforum_threads (sf_page_id);

CREATE INDEX sf_thread_forum ON simpleforum_threads (sf_forum_page_id);

CREATE INDEX sf_thread_last ON simpleforum_threads (sf_last_reply);
