-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_forums.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE simpleforum_forums (
  sf_forum_id BIGSERIAL NOT NULL,
  sf_page_id BIGINT NOT NULL,
  sf_title VARCHAR(255) NOT NULL,
  sf_created TIMESTAMPTZ NOT NULL,
  sf_creator BIGINT NOT NULL,
  PRIMARY KEY(sf_forum_id)
);

CREATE UNIQUE INDEX sf_forum_page ON simpleforum_forums (sf_page_id);

CREATE INDEX sf_forum_title ON simpleforum_forums (sf_title);
