-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_threads.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simpleforum_threads (
  sf_thread_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  sf_page_id BIGINT UNSIGNED NOT NULL,
  sf_forum_page_id BIGINT UNSIGNED NOT NULL,
  sf_subject VARCHAR(255) NOT NULL,
  sf_created BLOB NOT NULL,
  sf_creator BIGINT UNSIGNED NOT NULL,
  sf_last_reply BLOB DEFAULT NULL,
  sf_last_reply_user BIGINT UNSIGNED DEFAULT NULL
);

CREATE UNIQUE INDEX sf_thread_page ON /*_*/simpleforum_threads (sf_page_id);

CREATE INDEX sf_thread_forum ON /*_*/simpleforum_threads (sf_forum_page_id);

CREATE INDEX sf_thread_last ON /*_*/simpleforum_threads (sf_last_reply);
