-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_forums.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simpleforum_forums (
  sf_forum_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  sf_page_id BIGINT UNSIGNED NOT NULL,
  sf_title VARCHAR(255) NOT NULL,
  sf_created BLOB NOT NULL,
  sf_creator BIGINT UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX sf_forum_page ON /*_*/simpleforum_forums (sf_page_id);

CREATE INDEX sf_forum_title ON /*_*/simpleforum_forums (sf_title);
