-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_thread_props.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simpleforum_thread_props (
  sf_page_id BIGINT UNSIGNED NOT NULL,
  sf_locked SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(sf_page_id)
);
