-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_forums.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simpleforum_forums (
  sf_forum_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  sf_page_id BIGINT UNSIGNED NOT NULL,
  sf_title VARCHAR(255) NOT NULL,
  sf_created BINARY(14) NOT NULL,
  sf_creator BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX sf_forum_page (sf_page_id),
  INDEX sf_forum_title (sf_title),
  PRIMARY KEY(sf_forum_id)
) /*$wgDBTableOptions*/;
