-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables/simpleforum_threads.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simpleforum_threads (
  sf_thread_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  sf_page_id BIGINT UNSIGNED NOT NULL,
  sf_forum_page_id BIGINT UNSIGNED NOT NULL,
  sf_subject VARCHAR(255) NOT NULL,
  sf_created BINARY(14) NOT NULL,
  sf_creator BIGINT UNSIGNED NOT NULL,
  sf_last_reply BINARY(14) DEFAULT NULL,
  sf_last_reply_user BIGINT UNSIGNED DEFAULT NULL,
  UNIQUE INDEX sf_thread_page (sf_page_id),
  INDEX sf_thread_forum (sf_forum_page_id),
  INDEX sf_thread_last (sf_last_reply),
  PRIMARY KEY(sf_thread_id)
) /*$wgDBTableOptions*/;
